console.log('Hello world')
console.log('Hello Hacktiv8')
console.log('Hello Hacktiv8')
console.log('Hello Hacktiv8')
console.log('Hello Hacktiv8')

console.log('Godzilla')
console.log('Kong')
console.log('Mothra')console.log('Godzilla')
console.log('Kong')
console.log('Mothra')console.log('Godzilla')
console.log('Kong')
console.log('Mothra')console.log('Godzilla')
console.log('Kong')
console.log('Mothra')console.log('Godzilla')
console.log('Kong')
console.log('Mothra')